apiVersion: v1
kind: Secret
metadata:
  name: csi-tencentcloud
data:
  # value need base64 encoding
  #   echo -n "<SECRET_ID>" | base64
  STORAGE_API_SECRET_ID: "<SECRET_ID>"
  STORAGE_API_SECRET_KEY: "<SECRET_KEY>"
