FROM golang:1.14.1-stretch as builder

ADD . /go/src/github.com/github.com/von1994/CSIFramework

WORKDIR /go/src/github.com/github.com/von1994/CSIFramework

RUN CGO_ENABLED=0 GOOS=linux GOARCH=${TARGETARCH} go build -a -ldflags '-extldflags "-static"' -v -o /go/src/bin/csi-cbs cmd/cbs/main.go




FROM alpine:3.14.2

RUN apk add e2fsprogs xfsprogs findmnt blkid e2fsprogs-extra

COPY --from=builder /go/src/bin/csi-cbs /csi-cbs
RUN chmod +x /csi-cbs
CMD ["/csi-cbs"]
